apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: ollama
spec:
  selector:
    matchLabels:
      name: openwebuipd
  template:
    metadata:
      labels:
        name: openwebuipd
    spec:
      nodeSelector:
        target: "ui"
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: OLLAMA_BASE_URL
          value: http://ollamaservice:8081
        - name: WEBUI_SECRET_KEY
          value: 
